default: &default
  conference_batch:
    cron: '* */6 * * *'
    class: 'ConferenceBatchJob'
    queue: default

  create_tweets:
    cron: '* */6 * * *'
    class: 'CreateTweetsJob'
    queue: default

test: &test

development: &development
  << : *default

staging: &staging
  << : *default

production: &production
  << : *default
