default: &default
  conference_batch:
    cron: '0 */6 * * *'
    class: 'ConferenceBatchJob'
    queue: "conference-opportunities_<%= ENV.fetch('RAILS_ENV', 'development') %>_default"

  create_tweets:
    cron: '0 */6 * * *'
    class: 'CreateTweetsJob'
    queue: "conference-opportunities_<%= ENV.fetch('RAILS_ENV', 'development') %>_default"

  twitter_monitor:
    cron: '* * * * *'
    class: 'TwitterMonitorJob'
    queue: "conference-opportunities_<%= ENV.fetch('RAILS_ENV', 'development') %>_default"

test: &test

development: &development
  << : *default

staging: &staging
  << : *default

production: &production
  << : *default
